---
image: "buluma/github-action-molecule:4.0.5"

services:
  - docker:dind

variables:
  DOCKER_HOST: "tcp://docker:2375"
  PY_COLORS: 1

molecule:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
  retry: 1
  parallel:
    matrix:
      - image: "alpine"
        tag: "latest"
      - image: "debian"
        tag: "bullseye"
      - image: "debian"
        tag: "bookworm"
      - image: "fedora"
        tag: "34"
      - image: "fedora"
        tag: "latest"
      - image: "fedora"
        tag: "rawhide"
      - image: "docker-ubuntu2004-ansible"
        tag: "latest"
      - image: "ubuntu"
        tag: "bionic"

molecule-testing:
  script:
    - image=${image} tag=${tag} molecule test
  rules:
    - if: $CI_COMMIT_REF_NAME == "testing"
  retry: 2
  parallel:
    matrix:
      - image: "docker-ubuntu2004-ansible"
        tag: "latest"

galaxy:
  script:
    - ansible-galaxy role info ${CI_PROJECT_NAMESPACE}.sysctl
